# Generated by Django 5.1.4 on 2024-12-14 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('categorias', models.CharField(max_length=100)),
                ('detalhes', models.CharField(max_length=200)),
                ('ativo', models.BooleanField()),
                ('id_locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadras', to='myapp.locador')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('data_hora_terminio', models.DateTimeField()),
                ('id_locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='myapp.locatario')),
                ('id_quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='myapp.quadra')),
            ],
        ),
        migrations.AddField(
            model_name='locatario',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to='myapp.usuario'),
        ),
        migrations.AddField(
            model_name='locador',
            name='locador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locador', to='myapp.usuario'),
        ),
    ]
