# Generated by Django 5.1.4 on 2024-12-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_locador_locador_alter_locatario_locatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='cidade',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quadra',
            name='imagem',
            field=models.CharField(default=True, max_length=300),
        ),
        migrations.AddField(
            model_name='quadra',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
